### ISSUE TITLE
Links are not clickable in emails

### ISSUE THREAD

**Issue by karthiknmenon** [bigbinary/neeto-emails#4]
@ghousemohamed _a 
I recently got an invite to neetoChat, the `Accept Invitation` button is not clickable and doesn't have a link passed into it. 
The `neeto.com` in the footer is also not clickable. 

![image](https://user-images.githubusercontent.com/41678651/127213646-8b14b477-0398-44a5-87bd-10447f49bc62.png)

![image](https://user-images.githubusercontent.com/41678651/127213772-794f8f87-3985-4f30-821b-c8d1e1edc48a.png)

Please look into this.

**Comment by ghousemohamed** [comment]
I'm working on this. Can you move this email to your primary inbox in gmail. The link will be clickable then. Now currently it's thinking this email is a spam.
@karthiknmenon

**Comment by karthiknmenon** [comment]
@ghousemohamed The mail came under `Primary Inbox` for me. It was not tagged as spam.

**Comment by ghousemohamed** [comment]
@karthiknmenon https://www.loom.com/share/3c9669090c0b499e80d674cace1a3f79

**Comment by ghousemohamed** [comment]
@karthiknmenon This issue has been fixed.
